// <auto-generated />
using System;
using Asistente.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Asistente.Persistence.Database.Migrations
{
    [DbContext(typeof(AsistenteDbContext))]
    [Migration("20260816161356_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MAOSOL")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asistente.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DISPLAY_NAME");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("EXTERNAL_USER_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ACTIVO");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ULTIMO_INGRESO_UTC");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_ASIS_USUARIO_EXT");

                    b.HasIndex("Usuario")
                        .IsUnique()
                        .HasDatabaseName("UX_ASIS_USUARIO_LOGIN");

                    b.ToTable("ASIS_USUARIO", "MAOSOL");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("ACCION");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DETALLE");

                    b.Property<DateTime>("OcurridoEnUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OCURRIDO_EN_UTC");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkdayId");

                    b.ToTable("ASIS_AUDITORIA", "MAOSOL");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.TimeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREADO_EN_UTC");

                    b.Property<DateTime>("OcurridoEnUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OCURRIDO_EN_UTC");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("NVARCHAR2(24)")
                        .HasColumnName("TICKET_ID");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ASIS_EVENTO_CORR");

                    b.HasIndex("WorkdayId", "OcurridoEnUtc")
                        .HasDatabaseName("IX_ASIS_EVENTO_JOR_OCU");

                    b.ToTable("ASIS_EVENTO", "MAOSOL");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.WorkSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccionOrigen")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCION_ORIGEN");

                    b.Property<bool>("Editada")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("EDITADA");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FIN_UTC");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIO_UTC");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkdayId", "InicioUtc")
                        .HasDatabaseName("IX_ASIS_SESION_JOR_INI");

                    b.ToTable("ASIS_SESION", "MAOSOL", t =>
                        {
                            t.HasCheckConstraint("CK_ASIS_SESION_FIN", "FIN_UTC IS NULL OR FIN_UTC >= INICIO_UTC");
                        });
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaLocal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHA_LOCAL");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FIN_UTC");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INICIO_UTC");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FechaLocal")
                        .HasDatabaseName("IX_ASIS_JORNADA_USR_FECHA");

                    b.ToTable("ASIS_JORNADA", "MAOSOL");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Auditoria")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.TimeEvent", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Eventos")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.WorkSession", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Asistente.Domain.Entities.TicketRef", "Ticket", b1 =>
                        {
                            b1.Property<long>("WorkSessionId")
                                .HasColumnType("NUMBER(19)");

                            b1.Property<string>("ClienteId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("NVARCHAR2(16)")
                                .HasColumnName("CLIENTE_ID");

                            b1.Property<string>("ClienteNombre")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("NVARCHAR2(120)")
                                .HasColumnName("CLIENTE_NOMBRE");

                            b1.Property<string>("TicketId")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("NVARCHAR2(24)")
                                .HasColumnName("TICKET_ID");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("NVARCHAR2(200)")
                                .HasColumnName("TITULO");

                            b1.HasKey("WorkSessionId");

                            b1.ToTable("ASIS_SESION", "MAOSOL");

                            b1.WithOwner()
                                .HasForeignKey("WorkSessionId");
                        });

                    b.Navigation("Ticket")
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.OwnsOne("Asistente.Domain.Entities.TicketRef", "TicketPrincipal", b1 =>
                        {
                            b1.Property<long>("WorkdayId")
                                .HasColumnType("NUMBER(19)");

                            b1.Property<string>("ClienteId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("NVARCHAR2(16)")
                                .HasColumnName("TICKET_PRINCIPAL_CLIENTE_ID");

                            b1.Property<string>("ClienteNombre")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("NVARCHAR2(120)")
                                .HasColumnName("TICKET_PRINCIPAL_CLIENTE");

                            b1.Property<string>("TicketId")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("NVARCHAR2(24)")
                                .HasColumnName("TICKET_PRINCIPAL_ID");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("NVARCHAR2(200)")
                                .HasColumnName("TICKET_PRINCIPAL_TITULO");

                            b1.HasKey("WorkdayId");

                            b1.ToTable("ASIS_JORNADA", "MAOSOL");

                            b1.WithOwner()
                                .HasForeignKey("WorkdayId");
                        });

                    b.Navigation("TicketPrincipal");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Eventos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
