// <auto-generated />
using System;
using Asistente.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asistente.Persistence.Database.Migrations
{
    [DbContext(typeof(AsistenteDbContext))]
    partial class AsistenteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asistente.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVO");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("BLOQUEADO_HASTA_UTC");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CLAVE_HASH");

                    b.Property<DateTime>("FechaAltaUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_ALTA_UTC");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD_INTENTO_FALLIDO");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NOMBRE_COMPLETO");

                    b.Property<DateTime?>("UltimoCambioClaveUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMO_CAMBIO_CLAVE_UTC");

                    b.Property<DateTime?>("UltimoIngresoUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMO_INGRESO_UTC");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique()
                        .HasDatabaseName("UX_T_USUARIO_USUARIO");

                    b.ToTable("T_USUARIO", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ACCION");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DETALLE");

                    b.Property<DateTime>("OcurridoEnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OCURRIDO_EN_UTC");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("bigint")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkdayId")
                        .HasDatabaseName("IX_T_AUDITORIA_JORNADA");

                    b.ToTable("T_AUDITORIA", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Permiso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_T_PERMISO_CODIGO");

                    b.ToTable("T_PERMISO", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Planilla", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadFilas")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD_FILA");

                    b.Property<byte[]>("Contenido")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("CONTENIDO");

                    b.Property<DateTime>("GeneradaEnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("GENERADA_EN_UTC");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("HASH_SHA256");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NOMBRE_ARCHIVO");

                    b.Property<int>("NumeroGeneracion")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_GENERACION");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("bigint")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkdayId", "NumeroGeneracion")
                        .IsUnique()
                        .HasDatabaseName("UX_T_PLANILLA_JORNADA_GENERACION");

                    b.ToTable("T_PLANILLA", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.SesionUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Agente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AGENTE");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DIRECCION_IP");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FIN_UTC");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("INICIO_UTC");

                    b.Property<string>("MotivoCierre")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("MOTIVO_CIERRE");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InicioUtc")
                        .HasDatabaseName("IX_T_SESION_USUARIO_USUARIO_INICIO");

                    b.ToTable("T_SESION_USUARIO", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.TimeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CORRELACION_ID");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREADO_EN_UTC");

                    b.Property<DateTime>("OcurridoEnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OCURRIDO_EN_UTC");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("TICKET_ID");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("bigint")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_T_EVENTO_CORRELACION");

                    b.HasIndex("WorkdayId", "OcurridoEnUtc")
                        .HasDatabaseName("IX_T_EVENTO_JORNADA_OCURRIDO");

                    b.ToTable("T_EVENTO", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("PermisoId")
                        .HasColumnType("bigint")
                        .HasColumnName("PERMISO_ID");

                    b.Property<DateTime>("OtorgadoEnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OTORGADO_EN_UTC");

                    b.HasKey("UserId", "PermisoId");

                    b.HasIndex("PermisoId")
                        .HasDatabaseName("IX_T_USUARIO_PERMISO_PERMISO");

                    b.ToTable("T_USUARIO_PERMISO", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.WorkSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccionOrigen")
                        .HasColumnType("int")
                        .HasColumnName("ACCION_ORIGEN");

                    b.Property<bool>("Editada")
                        .HasColumnType("bit")
                        .HasColumnName("EDITADA");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FIN_UTC");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("INICIO_UTC");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TIPO");

                    b.Property<long>("WorkdayId")
                        .HasColumnType("bigint")
                        .HasColumnName("JORNADA_ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkdayId", "InicioUtc")
                        .HasDatabaseName("IX_T_SESION_JORNADA_INICIO");

                    b.ToTable("T_SESION", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_T_SESION_FIN", "FIN_UTC IS NULL OR FIN_UTC >= INICIO_UTC");
                        });
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO");

                    b.Property<DateTime>("FechaLocal")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA_LOCAL");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("FIN_UTC");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("INICIO_UTC");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USUARIO_ID");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FechaLocal")
                        .HasDatabaseName("IX_T_JORNADA_USUARIO_FECHA");

                    b.ToTable("T_JORNADA", "dbo");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Auditoria")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Planilla", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany()
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.SesionUsuario", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.TimeEvent", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Eventos")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asistente.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.WorkSession", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Workday", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Asistente.Domain.Entities.TicketRef", "Ticket", b1 =>
                        {
                            b1.Property<long>("WorkSessionId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ClienteId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("CLIENTE_ID");

                            b1.Property<string>("ClienteNombre")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("CLIENTE_NOMBRE");

                            b1.Property<string>("TicketId")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)")
                                .HasColumnName("TICKET_ID");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TITULO");

                            b1.HasKey("WorkSessionId");

                            b1.ToTable("T_SESION", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("WorkSessionId");
                        });

                    b.Navigation("Ticket")
                        .IsRequired();
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Asistente.Domain.Entities.TicketRef", "TicketPrincipal", b1 =>
                        {
                            b1.Property<long>("WorkdayId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ClienteId")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("TICKET_PRINCIPAL_CLIENTE_ID");

                            b1.Property<string>("ClienteNombre")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("TICKET_PRINCIPAL_CLIENTE_NOMBRE");

                            b1.Property<string>("TicketId")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)")
                                .HasColumnName("TICKET_PRINCIPAL_ID");

                            b1.Property<string>("Titulo")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TICKET_PRINCIPAL_TITULO");

                            b1.HasKey("WorkdayId");

                            b1.ToTable("T_JORNADA", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("WorkdayId");
                        });

                    b.Navigation("TicketPrincipal");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Workday", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Eventos");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
